spring:
  datasource:
    url: jdbc:mysql://192.168.1.122:3307/ureport2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 110
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis
mybatis:
  typeAliasesPackage: com.zz.hello.ureport2.entity
  mapperLocations: classpath:/mapper/*.xml


# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG

# ureport Mysql 存储
ureport.mysql.provider:
  prefix: zz-
  disabled: false

